default:
  image: "registry.gitlab.com/xenia-group/foxbuild:main"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'unstable'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_PIPELINE_SOURCE == 'schedule'

stages:
  - test
  - build
  - deploy

test-spec:
  stage: test
  script:
    - if [ "$BUILD_ALL" == 1 ]; then wget https://gitlab.com/xenia-group/foxbuild/-/raw/main/build_all.toml?ref_type=heads -O build.toml; else wget https://gitlab.com/xenia-group/foxbuild/-/raw/main/build_changed.toml?ref_type=heads -O build.toml; fi
    - if [ "$CI_COMMIT_BRANCH" == "" ]; then BRANCH="$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"; else BRANCH="$CI_COMMIT_BRANCH"; fi
    - sed -i "s/unstable/$BRANCH/g" build.toml
    - sed -i "s@https://gitlab.com/xenia-group/catalyst.git@$CI_PROJECT_URL@g" build.toml
    - cat build.toml
    - foxbuild -nc build.toml
  allow_failure: false

build-xenia:
  tags: 
    - saas-linux-2xlarge-amd64
  variables:
    MIRROR: "https://gentoo.osuosl.org/"
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$REPO_SSH_KEY"
    - ssh-add "$REPO_SSH_KEY"
  script:
    - if [ "$BUILD_ALL" == 1 ]; then wget https://gitlab.com/xenia-group/foxbuild/-/raw/main/build_all.toml?ref_type=heads -O build.toml; else wget https://gitlab.com/xenia-group/foxbuild/-/raw/main/build_changed.toml?ref_type=heads -O build.toml; fi
    - if [ "$CI_COMMIT_BRANCH" == "" ]; then BRANCH="$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"; else BRANCH="$CI_COMMIT_BRANCH"; fi
    - sed -i "s/unstable/$BRANCH/g" build.toml
    - sed -i "s@https://gitlab.com/xenia-group/catalyst.git@$CI_PROJECT_URL@g" build.toml
    - cat build.toml
    - foxbuild -ic build.toml
    - rsync -az -P -e "ssh -p 2 -o StrictHostKeyChecking=no" --exclude='Manifest.toml' --include='/*' --include="$CI_COMMIT_BRANCH**" --exclude='*' /var/foxbuild/output/* xenia@sakamoto.pl:/mnt/xenia/releases/.staging/
    - rsync -az -P -e "ssh -p 2 -o StrictHostKeyChecking=no" /var/foxbuild/output/Manifest.toml xenia@sakamoto.pl:/mnt/xenia/releases/.staging/
  allow_failure: false
  resource_group: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE != 'schedule'
    - if: $CI_COMMIT_BRANCH == 'unstable' && $CI_PIPELINE_SOURCE != 'schedule'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE != 'schedule'
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $SCHEDULE_FULL == "1"

deploy-xenia:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$REPO_SSH_KEY"
    - ssh-add "$REPO_SSH_KEY"
  script:
    - ssh -t xenia@sakamoto.pl "rsync -az -P --exclude='Manifest.toml' --include='/*' --include=\"$CI_COMMIT_BRANCH**\" --exclude='*' /mnt/xenia/releases/.staging/* /mnt/xenia/releases/"
    - ssh -t xenia@sakamoto.pl "rsync -az -P /mnt/xenia/releases/.staging/Manifest.toml /mnt/xenia/releases/"
  allow_failure: false
  resource_group: $CI_COMMIT_BRANCH
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $SCHEDULE_FULL == "1"
      when: on_success
    - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE != 'schedule'
      when: manual
    - if: $CI_COMMIT_BRANCH == 'unstable' && $CI_PIPELINE_SOURCE != 'schedule'
      when: manual
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE != 'schedule'
      when: manual
  retry: 2
