subarch: amd64
target: stage3
version_stamp: systemd-@TIMESTAMP@
rel_type: default
profile: default/linux/amd64/17.1/systemd/merged-usr
snapshot: 2023.03.12
source_subpath: default/stage1-amd64-systemd-@TIMESTAMP@
compression_mode: pixz
portage_confdir: /var/tmp/catalyst/config/stages
portage_prefix: releng
